"""
Liam Tran, July 3, 2025

Script based on JA's oligoShadowingJointProbabability.py script. I'm going to modify it to be more amenable working with ribosome shadowing data.

From JA's script:
    To do this, it'll first compute a reference probability of editing
    from a reference bc (input), *LT will need to modify this for chromosome*. 
    Will then use joint probability across
    a window (user input) of nts, and then display some number (10?) of
    reads, with position on the x-axis and y-axis as -logProb. Will
    also plot a summary metric...a metaRead plot, where x-axis is again
    position, and y-axis is...fraction of reads w/ a significant p-val?
    Not 100% on these metrics, so look at the code to ensure I didn't
    change my mind while I wrote the code.

Input: pickle2 - a pickled file, generated by shadowingBamToPickle.py, that contains a dictionary of reads. Each pickle belongs to a single chromosome. 
    refBg - probably a barcode but could also be another pickle, a "no oligo/ribosome" library *LT will need to modify this for chromosome, this would be a no ribosome control*. 
    window - probably 30, but whatever you want. This is in nts, not in
        number of sites (e.g., 30nts might have 4 As, or 10 As).
    numReads - will plot this many reads as examples
    oligoFile - line and space-delimited file of oligo boundaries. *LT will this be a file with expected ribosome boundaries?*

Output: might output some pickle files to make processing faster during
    writing this code.
    Plots of metaRead significant hits, with individual reads tiled 
        above that.

run as python3 oligoShadowingJointProbability.py pickle2 refBc window 
    numReads outPrefix
"""

import sys, common, pickle, collections, math, numpy, scipy.stats
from pyx import *

def parsePickleFile(pickleFile):
    """
    dataDict is of format:
    {readID:{edit_string,barcode,query_string,ref_string,aligned_pairs:...}}
    Will sort reads according to barcode, and output a tally of the number
    of reads per barcode. Will also compute the total size (in nts) of each
    barcode, to get a sense of coverage.
    
    Will output a dictionary of format:
    {bc:{readID:{position:edit}}}
    """
    ##start by unpickling the input file
    with open(pickleFile,'rb') as f:
        dataDict=pickle.load(f)
    ##
    aa=collections.defaultdict(lambda:collections.defaultdict(int))
    for readID,subDict in dataDict.items():
        bc=subDict['barcode']
        queryLength=len(subDict['read_sequence'])
        aa[bc]['ct']+=1
        aa[bc]['length']+=queryLength
    ##
    for k,v in aa.items():
        print('Barcode %s had %s sequences totaling %s kilo nts.'%(\
            k,v['ct'],v['length']/1000))
    ##
    bb=collections.defaultdict(lambda:collections.defaultdict(dict))
    ##
    for readID,subDict in dataDict.items():
        barCode=subDict['barcode']
        #print(barCode,readID)
        editString=subDict['edit_string']
        #print(editString,len(editString))
        readSeq=subDict['read_sequence_aligned']
        #print(readSeq,len(readSeq))
        refSeq=subDict['ref_sequence_aligned']
        #print(refSeq,len(refSeq))
        alignedPairs=subDict['aligned_pairs']
        #print(alignedPairs,len(alignedPairs))
        #sys.exit()
        for ii in range(len(alignedPairs)-1):
            entry=alignedPairs[ii]
            idx=entry[0]
            absIdx=entry[1]
            if idx!=None and absIdx!=None:
                seq=refSeq[ii]
                edit=editString[ii]
                if seq=='A' and edit!='2' and absIdx<=695:
                    ##695 is where the RT primer binds--anything past this
                    ##is artifact.
                    bb[barCode][readID][absIdx]=int(edit)
    ##
    return bb

def getBoundaryLocations(oligoFile):
    aa=[]
    with open(oligoFile,'r') as f:
        for line in f:
            line=line.strip().split()
            aa.append([entry for entry in map(int,line)])
    return aa

def getReferenceFreq(refDict):
    """
    refDict is of the format
    {readID:{position:edit}}
    For every position, will compute a frequency of edit and a frequency of 
    nonedit, and output it as:
    {position:(freq0,freq1)}
    """
    aa=collections.defaultdict(list)
    for readID,positionDict in refDict.items():
        for position,editStatus in positionDict.items():
            aa[position].append(editStatus)
    ##aa is of the format {position:[0,1,1,0,0,0,1,1,1,],...}
    bb={}
    for position,editList in aa.items():
        freq0=editList.count(0)/len(editList)
        freq1=editList.count(1)/len(editList)
        bb[position]=(freq0,freq1)
    ##
    return bb

def computeJointProbabilitiesPerRead(editFreqPerRead,referenceFreq,ntWindow):
    """
    editFreqPerRead=
    {bc:readID:position:edit/not}
    referenceFreq={position:(freq0,freq1)
    For every readID, will scan from 0 through 695 and if there's at least three
    sites in that window, will compute the joint probability. Will return:
    {bc:readID:[(position,prob),...]
    where positions are ordered
    """
    print('#####\nComputing joint probabilities for every read...\n#####')
    ##
    aa=collections.defaultdict(lambda:collections.defaultdict(list))
    ##
    N=1000
    print('Limiting to %s reads per sample...'%(N))
    cntr=0
    for bc,readDict in editFreqPerRead.items():
        for readID,positionDict in readDict.items():
            cntr+=1
            for ii in range(0,695,1):
                temp=[]
                for jj in range(ii,ii+ntWindow):
                    if jj in positionDict:
                        editVal=positionDict[jj]
                        temp.append(referenceFreq[jj][editVal])
                if len(temp)>=5:
                    jointProb=math.prod(temp)
                    aa[bc][readID].append((ii+ntWindow/2.,jointProb))
            if cntr==N:
                print('Done w/ barcode %s after %s reads.'%(bc,cntr))
                cntr=0
                break
        if cntr!=0:
            print('Done w/ barcode %s after %s reads.'%(bc,cntr))
            cntr=0
    ##
    return aa

def computeJointProbabilitiesPerRead_fromPickles(editFreqPerRead,refFreqPerBC,ntWindow):
    """
    editFreqPerRead=
    {bc:readID:position:edit/not}
    referenceFreq={position:(freq0,freq1)
    For every readID, will scan from 0 through 695 and if there's at least three
    sites in that window, will compute the joint probability. Will return:
    {bc:readID:[(position,prob),...]
    where positions are ordered
    """
    print('#####\nComputing joint probabilities for every read...\n#####')
    ##
    aa=collections.defaultdict(lambda:collections.defaultdict(list))
    ##
    N=1000
    print('Limiting to %s reads per sample...'%(N))
    cntr=0
    for bc,readDict in editFreqPerRead.items():
        refFreq =refFreqPerBC[bc]
        
        for readID,positionDict in readDict.items():
            cntr+=1
            for ii in range(0,695,1):
                temp=[]
                for jj in range(ii,ii+ntWindow):
                    if jj in positionDict and jj in refFreq: # added to only use refFreq for positions that are in the read, this could happen when comparing to different reference contigs
                        editVal=positionDict[jj]
                        temp.append(refFreq[jj][editVal]) # does this break at around 50% editing? 
                if len(temp)>= 5:
                    jointProb=math.prod(temp)
                    aa[bc][readID].append((ii+ntWindow/2.,jointProb))
            if cntr==N:
                print('Done w/ barcode %s after %s reads.'%(bc,cntr))
                cntr=0
                break
        if cntr!=0:
            print('Done w/ barcode %s after %s reads.'%(bc,cntr))
            cntr=0
    ##
    return aa

def plot_prob_edit_vs_nonedit(jointProbabilitiesPerRead, oligoLocations, outPrefix):
    pass

def getMetaReadPerBarcode(jointProbabilitiesPerRead):
    """
    jointProbabilitiesPerRead=
    {bc:readID:[(x,prob),...]}
    For all readIDs w/in one bc, will get summary metrics of the probs for each
    x, returning a dict of the format:
    {bc:[(x,quartile25,median,quartile75),...]}
    """
    print('#####\nMaking metaRead of joint probabilities...\n#####')
    ##
    aa=collections.defaultdict(lambda:collections.defaultdict(list))
    for bc,readDict in jointProbabilitiesPerRead.items():
        for readID,valList in readDict.items():
            for entry in valList:
                aa[bc][entry[0]].append(entry[1])
    ##
    ##aa is of the format:
    ##{bc:position:[value list of probs]}
    bb={}
    for bc,positionDict in aa.items():
        ##initialize the dict
        bb[bc]=[]
        ##
        tempList=[entry for entry in positionDict.keys()]
        tempList.sort()
        ##
        for position in tempList:
            freqVals=positionDict[position]
            bb[bc].append((position,\
                -math.log(numpy.quantile(freqVals,0.05),10),\
                -math.log(numpy.quantile(freqVals,0.5),10),\
                -math.log(numpy.quantile(freqVals,0.95),10)))
    ##
    print('Did top/bottom deciles rather than quartiles...')
    return bb

def mkMetaPlot(metaReadJointProb,oligoLocations,outPrefix):
    """
    oligoLocations=[(x1,x2),...(xn,xn+1)]
    metaReadJointProb=
    {bc:[(x,prob25,prob50,prob75)...]
    """
    print('Plotting meta read plot for each barcode...')
    print('Drawing boundary locations: ',oligoLocations)
    ##
    colors=[color.cmyk(0,0,0,1),
        color.cmyk(1,0.5,0,0),
        color.cmyk(0.1,0.05,0.9,0),
        color.cmyk(0.97,0,0.75,0),
        color.cmyk(0.5,0.5,0,0)]
    ##
    bcs=['bc5','bc1','bc2','bc3','bc4',]
    bcs.reverse()
    colors.reverse()
    ##
    c=canvas.canvas()
    ##
    for ii in range(len(bcs)):
        bc=bcs[ii]
        ##
        g=graph.graphxy(width=8,height=2,ypos=ii*3.5,
            x=graph.axis.linear(min=0,max=700,
                title='Position Along Txt (nt)'),
            y=graph.axis.linear(min=0,max=15,title='-log10 Prob'))
        ##
        for oligo in oligoLocations:
            leftBound=oligo[0]
            rightBound=oligo[1]
            c.fill(path.rect(g.width*leftBound/700,g.ypos,
                g.width*(rightBound-leftBound)/700,2),
                [deco.filled([color.cmyk(0,0,0,0.2),
                    color.transparency(0.2)])])
        ##
        ##plot the median
        g.plot(graph.data.points(metaReadJointProb[bc],x=1,y=3,
            title=bc),[graph.style.line([style.linestyle.solid,
                colors[ii]])])
        ##plot the quartiles
        g.plot(graph.data.points(metaReadJointProb[bc],x=1,y=2,
            title=bc),[graph.style.line([style.linestyle.dotted,
                colors[ii]])])
        g.plot(graph.data.points(metaReadJointProb[bc],x=1,y=4,
            title=bc),[graph.style.line([style.linestyle.dotted,
                colors[ii]])])
        ##
        c.insert(g)
    ##
    c.writePDFfile(outPrefix)

def main(args):
    ##
    pickleFile,referenceBackground,ntWindow,numberOfReadsToPlot,\
        boundaryFile,outPrefix=args[0:]
    ##
    locations=getBoundaryLocations(boundaryFile)
    ##extract the edit information from the pickle file
    editFreqPerRead=parsePickleFile(pickleFile)
    if referenceBackground.endswith('.pickle'):
        refFreqPerRead=parsePickleFile(referenceBackground)
        ##get the reference frequencies of the reference barcode
        refFreq_dict={}
        for bc,readDict in refFreqPerRead.items():
            refFreq_dict[bc]=getReferenceFreq(readDict)
        # print(refFreq_dict['bc1'])
        ##compute the joint probabilities per read
        jointProbabilitiesPerRead=computeJointProbabilitiesPerRead_fromPickles(\
            editFreqPerRead,refFreq_dict,int(ntWindow))
    else:
        ##get the reference frequencies of the reference barcode
        referenceFreq=getReferenceFreq(editFreqPerRead[referenceBackground])
        # print(referenceFreq)
        jointProbabilitiesPerRead=computeJointProbabilitiesPerRead(editFreqPerRead,\
        referenceFreq,int(ntWindow))
    ##referenceFreq is of the format {position:(freq0,freq1),...}
    ##
    ##Will use those reference frequencies to compute the joint probability
    ##of observing a given sequence of edits.
    # jointProbabilitiesPerRead=computeJointProbabilitiesPerRead(editFreqPerRead,\
    #     referenceFreq,int(ntWindow))
    metaReadJointProb=getMetaReadPerBarcode(jointProbabilitiesPerRead)
    ##
    mkMetaPlot(metaReadJointProb,locations,outPrefix+'.meta')

if __name__=='__main__':
    main(sys.argv[1:])    




