'''
Liam Tran, July 25  2025

This code will perform a PCA on a library of reads treated with TadA. Specifically, it will perform the analysis on binary strings where 1 indicates an edit and 0 indicates no edit.

input: pickle, a pickled file, generated by shadowingBamToPickle.py, that contains a dictionary of reads. Each pickle belongs to a single chromosome.
output: a numpy array of shape (n_samples, n_components) where n_samples is the number of reads and n_components is the number of principal components.
        A plot of the first two principal components will also be generated and saved as a PNG file.

Some ideas: remove A information?
'''


from sklearn.decomposition import PCA
import prince
import numpy as np
import mca

import sys, common, pickle, collections, math, numpy, scipy.stats
from pyx import *
from icecream import ic

def parsePickleFile(pickleFile):
    """
    dataDict is of format:
    {readID:{edit_string,barcode,query_string,ref_string,aligned_pairs:...}}
    Will sort reads according to barcode, and output a tally of the number
    of reads per barcode. Will also compute the total size (in nts) of each
    barcode, to get a sense of coverage.
    
    Will output a dictionary of format:
    {bc:{readID:{position:edit}}}
    """
    ##start by unpickling the input file
    with open(pickleFile,'rb') as f:
        dataDict=pickle.load(f)
    ##
    aa=collections.defaultdict(lambda:collections.defaultdict(int))
    for readID,subDict in dataDict.items():
        bc=subDict['barcode']
        queryLength=len(subDict['read_sequence'])
        aa[bc]['ct']+=1
        aa[bc]['length']+=queryLength
    ##
    for k,v in aa.items():
        print('Barcode %s had %s sequences totaling %s kilo nts.'%(\
            k,v['ct'],v['length']/1000))
    ##
    bb=collections.defaultdict(lambda:collections.defaultdict(dict))
    ##
    for readID,subDict in dataDict.items():
        barCode=subDict['barcode']
        #print(barCode,readID)
        editString=subDict['edit_string']
        #print(editString,len(editString))
        readSeq=subDict['read_sequence_aligned']
        #print(readSeq,len(readSeq))
        refSeq=subDict['ref_sequence_aligned']
        #print(refSeq,len(refSeq))
        alignedPairs=subDict['aligned_pairs']
        #print(alignedPairs,len(alignedPairs))
        #sys.exit()
        for ii in range(len(alignedPairs)-1):
            entry=alignedPairs[ii]
            idx=entry[0]
            absIdx=entry[1]
            if idx!=None and absIdx!=None:
                seq=refSeq[ii]
                edit=editString[ii]
                if seq=='A' and edit!='2' and absIdx<=695:
                    ##695 is where the RT primer binds--anything past this
                    ##is artifact.
                    bb[barCode][readID][absIdx]=int(edit)
    ##
    return bb

def make_data_frame(read_dict):
    """
    Convert the read dictionary into a DataFrame suitable for MCA.
    Each row corresponds to a read, and each column corresponds to a position in the reference sequence. 

    I will also add a 'barcode' column to the DataFrame for grouping purposes.
    """
    import pandas as pd
    data = []
    

    for bc, reads in read_dict.items():
        for readID, positions in reads.items():
            # Create a binary string for each read
            binary_string = [0] * 696  # Assuming positions are from 0 to 695
            for pos, editStatus in positions.items():
                binary_string[pos] = editStatus
            # Append the barcode and binary string to the data list
            data.append([readID]+ [bc] + binary_string)
            

    # Create a DataFrame
    columns = ['readID', 'barcode'] + [f'pos_{i}' for i in range(696)]
    df = pd.DataFrame(data, columns=columns)
    
    return df

def get_adenosine_positions(ref_seq):
    """
    Get the positions of adenosine in the reference sequence.
    Returns a list of positions where adenosine is present.
    """
    adenosine_positions = []
    for i, base in enumerate(ref_seq.upper()):
        if base == 'A':
            adenosine_positions.append(i)
    return adenosine_positions

def fitting_function(df, n_components=10,
    n_iter=3,
    copy=True,
    check_input=True,
    engine='sklearn',
    random_state=42):
    """
    Performs MCA fitting with prince library.
    """
    mca = prince.MCA(
        n_components=n_components,
        n_iter=n_iter,
        copy=copy,
        check_input=check_input,
        engine=engine,
        random_state=random_state
    )
    
    # Fit the model
    mca = mca.fit(df)


    return mca, mca.eigenvalues_summary

def plot_MCA_results(mca_model, df,
    x_component=0,
    y_component=1,
    show_column_markers=True,
    show_row_markers=True,
    show_column_labels=False,
    show_row_labels=False,
    output_file='mca_plot.png'):
    """
    Plot the MCA results.
    fitted_df is a DataFrame with the MCA results.
    """
    plot = mca_model.plot(df,
        x_component=x_component,
        y_component=y_component,
        show_column_markers=show_column_markers,
        show_row_markers=show_row_markers,
        show_column_labels=show_column_labels,
        show_row_labels=show_row_labels
    )


    return plot 


def main(args):
    if len(args) < 3:
        print("Usage: python oligoShadowing_PCA.py <pickle_file> <reference_fasta> <outprefix>")
        sys.exit(1)

    pickle_file = args[1]
    ref_fasta = args[2]
    outprefix = args[3]

    # Parse the pickle file
    read_dict = parsePickleFile(pickle_file)

    # Load the reference sequence
    from Bio import SeqIO
    ref_dict = SeqIO.to_dict(SeqIO.parse(ref_fasta, 'fasta'))

    
    
    # convert to DataFrame
    df = make_data_frame(read_dict)
    print(f"DataFrame shape: {df.shape}")
    print(df.head())

    # Perform MCA fitting
    print("Fitting MCA model...")
    fitted_model, eigenvalues_summary = fitting_function(df)
    print(eigenvalues_summary)

    print("MCA model fitted.")
    # Plot the results
    # print("Plotting MCA results...")
    # plot_MCA_results(fitted_model, df, output_file=outprefix + '_mca_plot.png')
    # print("Done!")
if __name__ == "__main__":
    main(sys.argv)
