'''
Liam Tran, July 16 2025

This is a long overdue script that will compute the log2FC of editing between two libraries or two sets of reads aligned to different contigs (ex: translatable vs untranslatable nanoluc reads).

To do this, I will compute the fraction of edits at each reference position for each library, and then compute the log2FC of these fractions.

Input: pickle, a pickled file, generated by shadowingBamToPickle.py, that contains a dictionary of reads. Each pickle belongs to a single chromosome. 
        reference: a fasta file containing the reference sequence for the chromosome.
        window: an integer, the size of the window to compute the frequency of edits over. Default is 30.
        locationFile: line and space-delimited file of location boundaries to highlight.
Output: a plot of the log2FC of editing at each position along the reference sequence, with the locations highlighted.
'''
import sys, common, pickle, collections, math, numpy, scipy.stats
from pyx import *
from icecream import ic

def parsePickleFile(pickleFile):
    """
    dataDict is of format:
    {readID:{edit_string,barcode,query_string,ref_string,aligned_pairs:...}}
    Will sort reads according to barcode, and output a tally of the number
    of reads per barcode. Will also compute the total size (in nts) of each
    barcode, to get a sense of coverage.
    
    Will output a dictionary of format:
    {bc:{readID:{position:edit}}}
    """
    ##start by unpickling the input file
    with open(pickleFile,'rb') as f:
        dataDict=pickle.load(f)
    ##
    aa=collections.defaultdict(lambda:collections.defaultdict(int))
    for readID,subDict in dataDict.items():
        bc=subDict['barcode']
        queryLength=len(subDict['read_sequence'])
        aa[bc]['ct']+=1
        aa[bc]['length']+=queryLength
    ##
    for k,v in aa.items():
        print('Barcode %s had %s sequences totaling %s kilo nts.'%(\
            k,v['ct'],v['length']/1000))
    ##
    bb=collections.defaultdict(lambda:collections.defaultdict(dict))
    ##
    for readID,subDict in dataDict.items():
        barCode=subDict['barcode']
        #print(barCode,readID)
        editString=subDict['edit_string']
        #print(editString,len(editString))
        readSeq=subDict['read_sequence_aligned']
        #print(readSeq,len(readSeq))
        refSeq=subDict['ref_sequence_aligned']
        #print(refSeq,len(refSeq))
        alignedPairs=subDict['aligned_pairs']
        #print(alignedPairs,len(alignedPairs))
        #sys.exit()
        for ii in range(len(alignedPairs)-1):
            entry=alignedPairs[ii]
            idx=entry[0]
            absIdx=entry[1]
            if idx!=None and absIdx!=None:
                seq=refSeq[ii]
                edit=editString[ii]
                if seq=='A' and edit!='2' and absIdx<=765:
                    ##765 is where the RT primer binds--anything past this
                    ##is artifact.
                    bb[barCode][readID][absIdx]=int(edit)
    ##
    return bb

def getBoundaryLocations(oligoFile):
    aa=[]
    with open(oligoFile,'r') as f:
        for line in f:
            line=line.strip().split()
            aa.append([entry for entry in map(int,line)])
    return aa

def getReferenceFreq(refDict):
    """
    refDict is of the format
    {readID:{position:edit}}
    For every position, will compute a frequency of edit and a frequency of 
    nonedit, and output it as:
    {position:(freq0,freq1)}
    """
    aa=collections.defaultdict(list)
    for readID,positionDict in refDict.items():
        for position,editStatus in positionDict.items():
            # ic(position,editStatus)
            aa[position].append(editStatus)
    ##aa is of the format {position:[0,1,1,0,0,0,1,1,1,],...}
    bb={}
    for position,editList in aa.items():
        freq0=editList.count(0)/len(editList)
        freq1=editList.count(1)/len(editList)
        bb[position]=(freq0,freq1)
    ##
    return bb

def smoothing(referenceFreq, ntWindow, start, end):
    """
    Takes a dictionary of reference frequencies and smooths it over a window. 
 
    referenceFreq is of the format {bc: {position:(freq0,freq1)}}
    ntWindow is an integer, the size of the window to smooth over.
    Returns a smoothed dictionary of the same format.
    """
    smoothedFreq = collections.defaultdict(lambda: collections.defaultdict(list))
    for bc, freqDict in referenceFreq.items():
        for position, (freq0, freq1) in freqDict.items():
            if start <= position < end:
                # Calculate the range for smoothing
                start_pos = max(start, position - ntWindow // 2)
                end_pos = min(end, position + ntWindow // 2)
                # Collect frequencies in the window
                window_freqs = [freqDict.get(pos, (0, 0)) for pos in range(start_pos, end_pos)]
                # Calculate smoothed frequencies
                smoothed_freq0 = sum(freq[0] for freq in window_freqs) / len(window_freqs)
                smoothed_freq1 = sum(freq[1] for freq in window_freqs) / len(window_freqs)
                smoothedFreq[bc][position] = (smoothed_freq0, smoothed_freq1)

    return smoothedFreq


def computeLog2FC(editFreq_dict1, editFreq_dict2):
    '''
    Returns a dictionary of log2 fold changes between two dictionaries of edit frequencies.

    editFreq_dict1 and editFreq_dict2 are dictionaries of the form:
    {bc: {position: (freq0, freq1)}}
    where freq0 is the frequency of non-edit and freq1 is the frequency of edit.
    
    The output is a dictionary of the form:
    {bc: {position: log2fc_nonedit, log2fc_edit}}
    where log2fc_nonedit = log2(freq0_2 / freq0_1) and log2fc_edit = log2(freq1_2 / freq1_1).
    '''
    print('Computing log2 fold change...')
    log2fc_dict = collections.defaultdict(lambda: collections.defaultdict(dict))
    
    for bc in editFreq_dict1.keys():
        for position in editFreq_dict1[bc].keys() | editFreq_dict2[bc].keys():
            freq1 = editFreq_dict1[bc].get(position, (0, 0))
            freq2 = editFreq_dict2[bc].get(position, (0, 0))
            if freq1[1] > 0 and freq2[1] > 0:
                log2fc_nonedit = math.log2((freq1[0] / freq1[1]) / (freq2[0] / freq2[1]))
                log2fc_edit = math.log2((freq1[1] / freq1[0]) / (freq2[1] / freq2[0]))
                log2fc_dict[bc][position] = (log2fc_nonedit, log2fc_edit)

    return log2fc_dict

def computeLog2FCFromBarcode(editFreq_dict, barcode):
    """
    Computes the log2 fold change of all barcodes editing against background barcode.

    """
    print('Computing log2 fold change for barcode %s...' % barcode)
    log2fc_dict = collections.defaultdict(dict)
    background_freq = editFreq_dict[barcode]

    for bc, freqDict in editFreq_dict.items():
        for position, (freq0, freq1) in freqDict.items():
            if position in background_freq:
                bg_freq0, bg_freq1 = background_freq[position]
                if bg_freq1 > 0 and freq1 > 0:
                    log2fc_nonedit = math.log2((bg_freq0 / bg_freq1) / (freq0 / freq1))
                    log2fc_edit = math.log2((bg_freq1 / bg_freq0) / (freq1 / freq0))
                    log2fc_dict[bc][position] = (log2fc_nonedit, log2fc_edit)

    return log2fc_dict

def getMetaReadPerBarcode(log2fc_dict):
    """
    log2fc_dict is a dictionary of the form {bc: {position: log2fc_nonedit, log2fc_edit}}.
    For all readIDs w/in one bc, will get summary metrics of the log2fc for each
    position, returning a dict of the format:
    {bc:[(x,quartile25,median,quartile75),...]}
    """
    print('#####\nMaking metaRead of log2fc...\n#####')
    ##
    aa=collections.defaultdict(lambda:collections.defaultdict(list))
    for bc,positionDict in log2fc_dict.items():
        for position,log2fc in positionDict.items():
            aa[bc][position].append(log2fc)
    ##
    ##aa is of the format:
    ##{bc:position:[value list of probs]}
    bb={}
    for bc,positionDict in aa.items():
        ##initialize the dict
        bb[bc]=[]
        ##
        tempList=[entry for entry in positionDict.keys()]
        tempList.sort()
        ##
        for position in tempList:
            freqVals=positionDict[position]
            bb[bc].append((position, freqVals[0][0], freqVals[0][1]))
    ##
    print('Did top/bottom deciles rather than quartiles...')
    return bb

def plotLog2FC(log2fc_meta_dict, bcDict, locations, outPrefix):
    """
    Plots the log2 fold change of editing at each position along the reference sequence.
    oligoLocations is a list of lists, where each sublist contains the start and end positions of an oligo.
    outPrefix is the prefix for the output file.

    log2fc_dict is a dictionary of the form {bc: {position: log2fc_nonedit, log2fc_edit}}.
    """
    print('Plotting meta read plot for each barcode...')
    print('Drawing boundary locations: ', locations)
    ##
    colors=[color.cmyk(0,0,0,1),
        color.cmyk(1,0.5,0,0),
        color.cmyk(0.1,0.05,0.9,0),
        color.cmyk(0.97,0,0.75,0),
        color.cmyk(0.5,0.5,0,0)]
    ##
    bcs = list(bcDict.keys())
    bcs.reverse()
    colors.reverse()
    ##
    c=canvas.canvas()
    ##
    for ii in range(len(bcs)):
        bc=bcs[ii]
        ##
        g=graph.graphxy(width=8,height=2,ypos=ii*3.5,
            x=graph.axis.linear(min=0,max=700,
                title='Position Along Txt (nt)'),
            y=graph.axis.linear(min=-3,max=3,title='log2FC'))
        #add horizontal line at 0
        g.plot(graph.data.points([(0,0),(700,0)],x=1,y=2,title='Zero Line'),
            [graph.style.line([style.linestyle.dotted, color.cmyk(0,0,0,1)])])
        
        ##
        for loc in locations:
            leftBound=loc[0]
            rightBound=loc[1]
            c.fill(path.rect(g.width*leftBound/700,g.ypos,
                g.width*(rightBound-leftBound)/700,2),
                [deco.filled([color.cmyk(0,0,0,0.2),
                    color.transparency(0.2)])])
        ##
        ##plot the log2FC of edits
        g.plot(graph.data.points(log2fc_meta_dict[bc],x=1,y=3,
            title=bc),[graph.style.line([style.linestyle.solid, colors[ii]])])
        # ##plot the quartiles
        # g.plot(graph.data.points(log2fc_meta_dict[bc],x=1,y=2,
        #     title=bc),[graph.style.line([style.linestyle.dotted,
        #         colors[ii]])])
        # g.plot(graph.data.points(log2fc_meta_dict[bc],x=1,y=4,
        #     title=bc),[graph.style.line([style.linestyle.dotted,
        #         colors[ii]])])
        ##
        c.insert(g)
    ##
    c.writePDFfile(outPrefix)

def parseBCFile(bcFile):
    '''
    Barcode file is a tab separated file with barcodes mapped to sample names.
    '''
    bc_dict = {}
    with open(bcFile, 'r') as f:
        for line in f:
            line = line.rstrip().split()

            if len(line) == 2:
                barcode, sample_name = line
                bc_dict[barcode] = sample_name
    return bc_dict


def main(args):
    if len(args) < 4:
        print('Usage: python shadowingLog2FC.py <pickleFile1> <background> <locationFile> <bcFile> <outPrefix> [ntWindow]')
        sys.exit(1)
    
    pickleFile1 = args[0]
    backgroundFile = args[1]
    locationFile = args[2]
    bcFile = args[3]
    outPrefix = args[4]
    ntWindow = int(args[5]) if len(args) > 5 else 30

    bcDict = parseBCFile(bcFile)

    if backgroundFile.endswith('.pickle'):
        pickleFile2 = backgroundFile
        # Parse the pickle files
        print(f'Parsing file {pickleFile1}...')
        refDict1 = parsePickleFile(pickleFile1)
        print(f'Parsing file {pickleFile2}...')
        refDict2 = parsePickleFile(pickleFile2)
        
        # Get the reference frequencies
        pickle_dict1 = {}
        for bc, readDict in refDict1.items():
            pickle_dict1[bc] = getReferenceFreq(readDict)
        pickle_dict2 = {}
        for bc, readDict in refDict2.items():
            pickle_dict2[bc] = getReferenceFreq(readDict)

        # Smooth the reference frequencies
        smoothedFreq1 = smoothing(pickle_dict1, ntWindow, 0, 695)
        smoothedFreq2 = smoothing(pickle_dict2, ntWindow, 0, 695)

        # Compute the log2 fold change
        print(f'Computing log2 fold change between {pickleFile1} and {pickleFile2}...')
        log2fc_dict = computeLog2FC(smoothedFreq1, smoothedFreq2)
        # print(log2fc_dict)

        # Get boundaries to highlight
        boundaryLocations = getBoundaryLocations(locationFile)

        # Plot the log2 fold change
        log2fc_meta_dict = getMetaReadPerBarcode(log2fc_dict)
        plotLog2FC(log2fc_meta_dict, bcDict, boundaryLocations, outPrefix+ '_log2fc')
    else:
        # backgroundFile is a bc
        print(f'Parsing file {pickleFile1}...')
        refDict1 = parsePickleFile(pickleFile1)

        # Get the reference frequencies
        pickle_dict1 = {}
        for bc, readDict in refDict1.items():
            pickle_dict1[bc] = getReferenceFreq(readDict)


        # Smooth the reference frequencies
        smoothedFreq1 = smoothing(pickle_dict1, ntWindow, 0, 695)
        ref_bg = smoothedFreq1[backgroundFile]

        # Get boundaries to highlight
        boundaryLocations = getBoundaryLocations(locationFile)
        
        # Compute the log2 fold change
        print(f'Computing log2 fold change for barcode {backgroundFile}...')
        log2fc_dict = computeLog2FCFromBarcode(smoothedFreq1, backgroundFile)

        # Get meta read per barcode
        log2fc_meta_dict = getMetaReadPerBarcode(log2fc_dict)
        # print(log2fc_meta_dict)

        # Plot the log2 fold change
        plotLog2FC(log2fc_meta_dict, bcDict, boundaryLocations, outPrefix + '_log2fc')

    print('Done!')
        

if __name__ == "__main__":
    main(sys.argv[1:])

    
